language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
install:
- python buildout-bootstrap.py
- bin/buildout annotate
- bin/buildout
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install coveralls
- coveralls
